spring:
  application:
    name: eureka-client

server:
  port: 21111

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      eureka-server-port: 11111
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.serviceUrl.eureka-server-port}/eureka/
